### ISSUE TITLE
How to fix HDMI?

### ISSUE THREAD

**Issue by trongthanht3** [mindcontrol1201/Msi-GF63-8RC--Bigsur-11.4-Hackintosh#1]
Hi, I have problem with my own OC that I can't fix HDMI port. Can you explain how you fix it? Thank you.

**Comment by mindcontrol1201** [comment]
Search for this Reddit post on google “Fix HDMI port (and possibly others) not working on Intel UHD 620” I used that guide to patch frame-buffer and it fixed HDMI issue, did you try my properties?

**Comment by trongthanht3** [comment]
Thanks for your reply. I tried your EFI, it works really good. Your EFI fixed almost everything of mine, but layout-id: 6 make speaker sound like in a box (i'm using 40 for better sound quality but external mic-in not working). I saw that you fixed HD Webcam by patching USB, I did the same thing but it just now work.

**Comment by mindcontrol1201** [comment]
what do you mean by external mic? are you talking about bluetooth mic? if thats your problem use latest  beta intelbluetoothkext and replace it in kext folder and update config file. webcam worked for me from first boot never had any issues with it, just had sleep issues initially and fixed it with usb patching.

**Comment by trongthanht3** [comment]
Yes, my microphone just not working so I changed layout-id to the same as your config but then speaker sound like a box. I fixed HDMI with your guide btw. Thanks a lot for your help 👍
